import re

base = '/Users/clawdbot/.openclaw/workspace/builds/qck-case-studies/case-studies'

replacements = {
    "flow-feet": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Vivobarefoot</div><div class='text-xs text-blue-400 mb-2'>Category Leader</div><div class='text-sm text-gray-400'>Dominates barefoot shoe search with deep editorial content and a loyal community that generates thousands of organic backlinks. Established as the definitive authority on foot health and natural movement.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Xero Shoes</div><div class='text-xs text-blue-400 mb-2'>DTC Content Brand</div><div class='text-sm text-gray-400'>Built a formidable DTC presence through consistent long-form blogging and an active community forum that fuels user-generated content, ranking across hundreds of barefoot and minimalist shoe queries.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Merrell</div><div class='text-xs text-blue-400 mb-2'>Retail Authority</div><div class='text-sm text-gray-400'>Merrell's massive retail footprint gives them domain authority that powers rankings across trail and minimalist shoe queries without proportional content investment.</div></div></div><p class='text-gray-400 text-sm'>Flow Feet's opportunity is in foot health education, barefoot transition guides, and long-tail product comparison queries where bigger brands publish broadly but specialists win with depth.</p></div>",
    "flowblend": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Gainful</div><div class='text-xs text-blue-400 mb-2'>Personalized Nutrition Brand</div><div class='text-sm text-gray-400'>Built their SEO moat around personalization content, owning queries about custom protein formulas and nutrition quizzes that drive high-intent traffic.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Orgain</div><div class='text-xs text-blue-400 mb-2'>Organic Protein Authority</div><div class='text-sm text-gray-400'>Combines massive retail distribution and substantial content investment to dominate both branded and category-level protein queries with clean-label positioning.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Garden of Life</div><div class='text-xs text-blue-400 mb-2'>Certification-Backed Authority</div><div class='text-sm text-gray-400'>Leverages third-party certifications and clinical research to rank authoritatively on supplement queries where E-E-A-T signals matter most.</div></div></div><p class='text-gray-400 text-sm'>FlowBlend's opportunity is in blend-specific education and ingredient transparency content where mega-brands publish broadly but smaller specialists win with precision.</p></div>",
    "fluidstance": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Topo</div><div class='text-xs text-blue-400 mb-2'>Ergonomic Mat Leader</div><div class='text-sm text-gray-400'>Dominates anti-fatigue mat and ergonomic standing accessory searches through a focused product catalog backed by strong review signals and retail placement.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Flexispot</div><div class='text-xs text-blue-400 mb-2'>Standing Desk Ecosystem</div><div class='text-sm text-gray-400'>Broad standing desk product ecosystem gives them authority across the full range of home office ergonomic queries, with an affiliate program that generates backlinks at scale.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Wirecutter</div><div class='text-xs text-blue-400 mb-2'>Editorial Gatekeeper</div><div class='text-sm text-gray-400'>Wirecutter's standing desk accessory roundups dominate SERP real estate and function as the primary gatekeeper for consumer purchase decisions in this category.</div></div></div><p class='text-gray-400 text-sm'>FluidStance's clearest opportunity is in balance board science, productivity research, and movement-at-work content where Wirecutter editorializes shallowly and product brands rarely invest in genuine depth.</p></div>",
    "fresh-bros": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Cannaflower</div><div class='text-xs text-blue-400 mb-2'>Premium Hemp Flower Brand</div><div class='text-sm text-gray-400'>Established strong content authority through strain education, terpene guides, and COA transparency content. Their editorial investment has made them a go-to resource for hemp flower quality research.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Tweedle Farms</div><div class='text-xs text-blue-400 mb-2'>Direct Competitor</div><div class='text-sm text-gray-400'>Farm-to-consumer narrative and editorial presence rank for many of the same hemp strain and effects queries, with authentic sourcing content that builds a loyal following.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Plain Jane</div><div class='text-xs text-blue-400 mb-2'>Review Dominant Brand</div><div class='text-sm text-gray-400'>Accumulated review authority through aggressive affiliate outreach and high volume of third-party coverage that dominates branded and category search results.</div></div></div><p class='text-gray-400 text-sm'>Fresh Bros' opportunity is in wholesale/bulk hemp flower queries, compliance and lab-testing education, and B2B-oriented content where consumer-focused competitors have left significant demand unaddressed.</p></div>",
    "fresh-pickle": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Bubbies</div><div class='text-xs text-blue-400 mb-2'>Fermented Food Authority</div><div class='text-sm text-gray-400'>Commands the naturally-fermented pickle space with decades of brand recognition, strong gut health positioning, and editorial mentions that reinforce their authority on fermented food queries.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Real Pickles</div><div class='text-xs text-blue-400 mb-2'>Craft Pickle Brand</div><div class='text-sm text-gray-400'>Occupies the craft, small-batch positioning with strong placement in food media and regional press that generates high-quality editorial backlinks and search authority.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Grillo's Pickles</div><div class='text-xs text-blue-400 mb-2'>DTC Brand SEO Success</div><div class='text-sm text-gray-400'>Cracked the DTC pickle market with a brand story compelling enough to earn food media coverage and social sharing that fuels organic discovery and brand search demand.</div></div></div><p class='text-gray-400 text-sm'>Fresh Pickle's opportunity is in artisan pickling education, brine recipes, fermentation how-tos, and gifting content where established brands publish little and consumer search intent is high.</p></div>",
    "giften-market": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Etsy</div><div class='text-xs text-blue-400 mb-2'>Dominant Marketplace</div><div class='text-sm text-gray-400'>Millions of product pages and massive domain authority allow Etsy to rank for virtually every personalized and custom gift query. Their UGC content model creates a self-perpetuating SEO engine impossible for smaller marketplaces to match head-on.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Uncommon Goods</div><div class='text-xs text-blue-400 mb-2'>Curated Gift Editorial</div><div class='text-sm text-gray-400'>Ranks prominently on gift guide queries through a curated editorial strategy positioning them as a trusted taste-maker. Their gift-for-every-occasion content captures high-intent shoppers searching for ideas rather than specific products.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Personal Creations</div><div class='text-xs text-blue-400 mb-2'>Personalized Gifts Leader</div><div class='text-sm text-gray-400'>Deep category authority in personalized gifts through a large catalog optimized for occasion, recipient, and item-type search combinations that captures intent at every stage of the gift-shopping journey.</div></div></div><p class='text-gray-400 text-sm'>Giften Market's SEO opportunity is in niche recipient and occasion combinations — gifts for specific professions, milestone moments, and cultural gifting traditions — where Etsy's scale becomes noise and curation wins.</p></div>",
    "head-rush-tech": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Petzl</div><div class='text-xs text-blue-400 mb-2'>Climbing Equipment Authority</div><div class='text-sm text-gray-400'>Global brand authority in climbing and vertical work safety translates into strong rankings across technical equipment, certification, and safety queries where E-E-A-T signals are essential.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Black Diamond</div><div class='text-xs text-blue-400 mb-2'>Gear Authority</div><div class='text-sm text-gray-400'>Strong editorial presence in climbing media and athlete sponsorships generates high-authority backlinks that reinforce their domain across aerial and climbing gear queries.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>REI</div><div class='text-xs text-blue-400 mb-2'>Mega-Retailer Domain</div><div class='text-sm text-gray-400'>REI's enormous domain authority allows their product and buying guide pages to rank for nearly any outdoor gear query. Their expert advice content gives them trust signals that specialty brands spend years building.</div></div></div><p class='text-gray-400 text-sm'>Head Rush Tech's opportunity is in aerial adventure park safety, belay device education, and institutional buyer queries — commercial and technical search intent that REI ignores and Petzl addresses only broadly.</p></div>",
    "hello-cake": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Maude</div><div class='text-xs text-blue-400 mb-2'>Premium Wellness Brand</div><div class='text-sm text-gray-400'>Positioned as the editorial authority in modern sexual wellness, earning placements in major lifestyle publications through content that normalizes and educates — generating high-quality backlinks disproportionate to their brand age.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>LELO</div><div class='text-xs text-blue-400 mb-2'>Luxury Brand Authority</div><div class='text-sm text-gray-400'>Years of aggressive PR have built a backlink profile that dominates high-intent purchase queries across the intimacy product category. Their international presence and influencer partnerships create brand search volume that lifts all organic rankings.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Unbound</div><div class='text-xs text-blue-400 mb-2'>DTC Content-Forward Brand</div><div class='text-sm text-gray-400'>Treats sexual wellness education as a top-of-funnel acquisition strategy, earning a long-tail content advantage by publishing on sensitive topics other brands avoid.</div></div></div><p class='text-gray-400 text-sm'>Hello Cake's opportunity is in couples-focused intimacy content and relationship wellness education where the category skews female-solo and leaves the couples market underserved in search.</p></div>",
    "holistic-heart-centers": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Cleveland Clinic</div><div class='text-xs text-blue-400 mb-2'>Medical Authority</div><div class='text-sm text-gray-400'>Physician-authored content and institutional domain authority make Cleveland Clinic the default SERP winner for nearly every heart health informational query. Their E-E-A-T signals set a benchmark that requires specialist-level content depth to approach.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>American Heart Association</div><div class='text-xs text-blue-400 mb-2'>Editorial Dominance</div><div class='text-sm text-gray-400'>The AHA's nonprofit authority and decades of patient education content give them an unassailable position on heart health informational queries. Their research citations create a backlink ecosystem reinforcing every page they publish.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Local Cardiology Practices</div><div class='text-xs text-blue-400 mb-2'>Geographic SEO Rivals</div><div class='text-sm text-gray-400'>At the local level, well-optimized cardiology and integrative medicine practices compete intensely for near-me and city-specific searches where local review volume and Google Business Profile optimization are the primary differentiators.</div></div></div><p class='text-gray-400 text-sm'>Holistic Heart Centers' opportunity is in integrative cardiology content — natural heart health protocols and holistic prevention — where Cleveland Clinic publishes conventionally and the AHA doesn't venture.</p></div>",
    "huckle-bee-farms": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Nature Nate's</div><div class='text-xs text-blue-400 mb-2'>Category Leader</div><div class='text-sm text-gray-400'>Dominates raw honey search through wide retail distribution, strong Amazon presence, and high review volume. Their scale generates the backlink profile and brand search demand that smaller producers must work around.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Bee Harmony</div><div class='text-xs text-blue-400 mb-2'>Retail Honey Brand</div><div class='text-sm text-gray-400'>Retail shelf presence and pollinator-conservation positioning earn consistent food media coverage and specialty grocery placements that generate quality editorial links and SEO authority.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Really Raw Honey</div><div class='text-xs text-blue-400 mb-2'>Artisan Honey Editorial</div><div class='text-sm text-gray-400'>Built credibility in the unprocessed honey niche through educational content about raw honey standards, giving them an editorial presence disproportionate to their size.</div></div></div><p class='text-gray-400 text-sm'>Huckle Bee Farms' opportunity is in varietal honey education, bee product health benefits, and local/regional honey sourcing content where artisan credibility outperforms retail scale.</p></div>",
    "instant": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Instant Pot Brand</div><div class='text-xs text-blue-400 mb-2'>First-Party Authority</div><div class='text-sm text-gray-400'>The Instant Pot brand owns their own keyword universe, ranking naturally for every accessory, recipe, and how-to query associated with their product line. Any competing brand must win on specificity and depth rather than brand authority.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>KitchenAid</div><div class='text-xs text-blue-400 mb-2'>Kitchen Brand Authority</div><div class='text-sm text-gray-400'>Broad kitchen appliance authority allows KitchenAid's accessory and recipe content to rank across a wide range of kitchen tool queries through domain strength alone.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>America's Test Kitchen</div><div class='text-xs text-blue-400 mb-2'>Editorial Gatekeeper</div><div class='text-sm text-gray-400'>Dominates recipe and appliance recommendation queries with rigorous testing content that consumers and search engines treat as the most trustworthy voice in kitchen gear.</div></div></div><p class='text-gray-400 text-sm'>Instant's opportunity is in accessory compatibility guides, pressure cooker troubleshooting, and model-specific upgrade content where first-party content stays promotional and ATK editorializes broadly.</p></div>",
    "intriguing-hair": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Nutrafol</div><div class='text-xs text-blue-400 mb-2'>Category Leader</div><div class='text-sm text-gray-400'>Invested heavily in clinical content and physician partnership programs that give them E-E-A-T authority across hair loss, thinning, and scalp health queries. Their content library creates a topical authority moat that smaller brands spend years trying to replicate.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Vegamour</div><div class='text-xs text-blue-400 mb-2'>DTC Editorial Brand</div><div class='text-sm text-gray-400'>Strong DTC editorial presence through influencer-driven content and consistent publishing keeps them visible across hair wellness search queries with plant-based positioning that earns clean beauty media placements.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Viviscal</div><div class='text-xs text-blue-400 mb-2'>Clinical Brand Review Authority</div><div class='text-sm text-gray-400'>Clinical trial backing and a review site presence built over decades give Viviscal strong conversion authority on purchase-intent hair growth queries where trust signals drive click decisions.</div></div></div><p class='text-gray-400 text-sm'>Intriguing Hair's opportunity is in scalp health education, condition-specific hair loss content, and ingredient comparison queries where Nutrafol publishes clinically and consumer brands publish superficially.</p></div>",
}

BOILERPLATE_PATTERN = re.compile(
    r'<p[^>]*>\s*Being absent from page 1 means losing customers.*?real buyer search behavior[^<]*(?:targeting[^<]*)?\s*</p>',
    re.DOTALL | re.IGNORECASE
)
BOILERPLATE_PATTERN2 = re.compile(
    r'Being absent from page 1 means losing customers.*?real buyer search behavior[^.]*\.',
    re.DOTALL | re.IGNORECASE
)

modified = []
for slug, new_section in replacements.items():
    path = f'{base}/{slug}/index.html'
    html = open(path).read()
    original = html
    replaced = False
    for pat in [BOILERPLATE_PATTERN, BOILERPLATE_PATTERN2]:
        match = pat.search(html)
        if match:
            html = html[:match.start()] + new_section + html[match.end():]
            replaced = True
            break
    if replaced:
        open(path, 'w').write(html)
        modified.append(slug)
        print(f"Fixed: {slug}")
    else:
        print(f"Pattern not found: {slug}")
print(f"\nModified: {len(modified)}/{len(replacements)}")
