import re, json

BOILERPLATE = "Being absent from page 1 means losing customers to competitors before they ever see your brand. The challenge: ranking for high-intent category terms means outranking established players with years of content authority and domain strength. Generic tactics don't work. What does is a systematic approach built around real buyer search behavior. QCK came in with a data-driven content strategy targeting"

# The boilerplate appears in a <p> tag inside a section - find and replace the full paragraph
BOILERPLATE_PATTERN = re.compile(
    r'<p[^>]*>\s*Being absent from page 1 means losing customers to competitors[^<]*</p>',
    re.DOTALL | re.IGNORECASE
)

# Also match the slightly longer version that continues after "targeting"
BOILERPLATE_PATTERN2 = re.compile(
    r'Being absent from page 1 means losing customers to competitors.*?real buyer search behavior\. QCK came in with a data-driven content strategy targeting[^<]*',
    re.DOTALL | re.IGNORECASE
)

base = '/Users/clawdbot/.openclaw/workspace/builds/qck-case-studies/case-studies'

replacements = {
    "airestech": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>DefenderShield</div><div class='text-xs text-blue-400 mb-2'>Content Authority</div><div class='text-sm text-gray-400'>Had locked up virtually every EMF education keyword with a deep library of long-form guides, making them the default reference for informational queries in the space.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Lambs</div><div class='text-xs text-blue-400 mb-2'>VC-Backed Challenger</div><div class='text-sm text-gray-400'>Flush with venture funding, Lambs was aggressively building out content and earning press coverage that translated directly into high-authority backlinks.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>SaferTech / EWG</div><div class='text-xs text-blue-400 mb-2'>Editorial Sites</div><div class='text-sm text-gray-400'>Non-commercial editorial domains with decades of trust signals dominated the top informational queries, crowding out product-first brands on awareness-stage keywords.</div></div></div><p class='text-gray-400 text-sm'>QCK identified mid-funnel buyer-intent gaps—terms like \"EMF protection device for home\" and device-specific queries—where commercial pages could outrank editorial content.</p></div>",
    "awe-inspired": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Energy Muse</div><div class='text-xs text-blue-400 mb-2'>Content Authority</div><div class='text-sm text-gray-400'>Built one of the largest crystal and chakra content libraries on the web, ranking for thousands of spiritual wellness terms and capturing the top of the funnel at scale.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Crystals.com</div><div class='text-xs text-blue-400 mb-2'>SEO-First Competitor</div><div class='text-sm text-gray-400'>A pure editorial and product SEO play with a keyword-optimized catalog that captured both informational and transactional searches across the category.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Alex and Ani</div><div class='text-xs text-blue-400 mb-2'>Brand + Retail Authority</div><div class='text-sm text-gray-400'>Massive brand recognition and retail distribution gave them powerful backlink profiles and click-through advantages on branded and semi-branded jewelry queries.</div></div></div><p class='text-gray-400 text-sm'>QCK targeted chakra-specific jewelry queries and gifting intent keywords where Awe Inspired's unique designs could convert browsers that broader crystal content sites couldn't close.</p></div>",
    "ballerina-farm": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>The Pioneer Woman</div><div class='text-xs text-blue-400 mb-2'>Media + Food Network Authority</div><div class='text-sm text-gray-400'>Backed by Food Network's domain authority and decades of editorial content, The Pioneer Woman was nearly untouchable on broad homestead cooking and farmhouse lifestyle keywords.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Farmhouse on Boone</div><div class='text-xs text-blue-400 mb-2'>Blog-First Lifestyle Brand</div><div class='text-sm text-gray-400'>A blog-first content operation with years of compounding SEO equity across homesteading, sourdough, and farmhouse living topics that drew massive organic traffic.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Lodge Cast Iron</div><div class='text-xs text-blue-400 mb-2'>Cookware Editorial Authority</div><div class='text-sm text-gray-400'>A legacy brand with strong editorial content around cast iron cooking that dominated product-adjacent recipe and technique queries in the homestead cooking space.</div></div></div><p class='text-gray-400 text-sm'>QCK found opportunity in brand-specific and community-driven queries around Ballerina Farm's viral content and product line, capturing demand that generic homestead publishers couldn't serve.</p></div>",
    "bedvoyage": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Cariloha</div><div class='text-xs text-blue-400 mb-2'>Bamboo Category Leader</div><div class='text-sm text-gray-400'>The dominant bamboo lifestyle brand with heavy SEO investment, retail locations, and a content operation that had staked out most high-volume bamboo bedding keywords.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Ettitude</div><div class='text-xs text-blue-400 mb-2'>Direct Content Competitor</div><div class='text-sm text-gray-400'>A direct-to-consumer bamboo bedding brand with a content-forward strategy targeting the same eco-conscious buyer keywords and earning strong editorial backlinks.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Cozy Earth</div><div class='text-xs text-blue-400 mb-2'>Celebrity-Endorsed Authority</div><div class='text-sm text-gray-400'>Celebrity endorsements and Oprah's Favorite Things placement generated a backlink profile and brand search volume that gave Cozy Earth outsized authority across luxury bedding queries.</div></div></div><p class='text-gray-400 text-sm'>QCK targeted eco-material comparison queries and sleep-quality keywords where BedVoyage's bamboo-specific expertise and certifications could win against broader luxury bedding competitors.</p></div>",
    "bibboards": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Bumkins</div><div class='text-xs text-blue-400 mb-2'>Baby Accessories Leader</div><div class='text-sm text-gray-400'>A category-leading baby accessories brand with strong product SEO, widespread retail distribution, and a loyal customer base that reinforced its rankings on core bib queries.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>OXO Tot</div><div class='text-xs text-blue-400 mb-2'>Brand + Retailer Authority</div><div class='text-sm text-gray-400'>OXO's parent brand authority combined with placement in every major retailer created a backlink and brand signal advantage that was difficult to challenge on high-volume baby product terms.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Review &amp; Editorial Sites</div><div class='text-xs text-blue-400 mb-2'>SERP Gatekeepers</div><div class='text-sm text-gray-400'>Parenting roundup publishers controlled the \"best baby bib\" queries that drive the most purchase-ready traffic, squeezing out brand pages.</div></div></div><p class='text-gray-400 text-sm'>QCK focused on accessory-specific and problem-aware queries—around mess containment and mealtime solutions—where BibBoards' magnetic innovation could differentiate against commodity bib results.</p></div>",
    "biopower-pet": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Zesty Paws</div><div class='text-xs text-blue-400 mb-2'>Category Leader</div><div class='text-sm text-gray-400'>The dominant pet supplement brand with a massive content budget, thousands of ranking product and educational pages, and a review footprint that made them the default result across the category.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>VetriScience</div><div class='text-xs text-blue-400 mb-2'>Vet-Backed Authority</div><div class='text-sm text-gray-400'>Veterinarian endorsements and clinical positioning gave VetriScience outsized trust signals on health-condition keywords where credibility heavily influences click-through and rankings.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>NaturVet</div><div class='text-xs text-blue-400 mb-2'>Retail Distribution + Brand Recognition</div><div class='text-sm text-gray-400'>Broad retail shelf presence and decades of brand recognition translated into strong branded search volume and retailer-generated backlinks that boosted organic visibility.</div></div></div><p class='text-gray-400 text-sm'>QCK targeted ingredient-specific and condition-aware queries—around gut health, joint support, and breed-specific needs—where BioPower Pet's formulations could rank against review aggregators and generalist brands.</p></div>",
}

modified = []
for slug, new_section in replacements.items():
    path = f'{base}/{slug}/index.html'
    html = open(path).read()
    original = html
    
    # Find and replace the boilerplate - it's inside a <p> tag, find the containing paragraph
    # Look for the sentence start in various wrappings
    patterns = [
        re.compile(r'<p[^>]*>\s*Being absent from page 1 means losing customers.*?real buyer search behavior[^<]*(?:targeting[^<]*)?\s*</p>', re.DOTALL | re.IGNORECASE),
        re.compile(r'Being absent from page 1 means losing customers.*?real buyer search behavior[^.]*\.', re.DOTALL | re.IGNORECASE),
    ]
    
    replaced = False
    for pat in patterns:
        match = pat.search(html)
        if match:
            html = html[:match.start()] + new_section + html[match.end():]
            replaced = True
            break
    
    if replaced:
        open(path, 'w').write(html)
        modified.append(slug)
        print(f"✅ Fixed: {slug}")
    else:
        print(f"⚠️  Pattern not found in: {slug} — manual check needed")

print(f"\nModified: {len(modified)}/{len(replacements)}")
