import re

base = '/Users/clawdbot/.openclaw/workspace/builds/qck-case-studies/case-studies'

replacements = {
    "brainrich-kids": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>SmartyPants</div><div class='text-xs text-blue-400 mb-2'>Category Leader</div><div class='text-sm text-gray-400'>Dominates kids supplement searches through massive retail distribution and an expansive content library. Their brand authority makes them the default result for broad category queries.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>MaryRuth Organics</div><div class='text-xs text-blue-400 mb-2'>DTC Brand</div><div class='text-sm text-gray-400'>A strong direct-to-consumer brand with deep content investment across kids health and nutrition topics. Their editorial presence captures parent-intent queries throughout the funnel.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Llama Naturals</div><div class='text-xs text-blue-400 mb-2'>Kids-First Brand</div><div class='text-sm text-gray-400'>Built specifically around kids wellness, earning strong review placement and comparison rankings. Their focused positioning allows them to rank competitively on niche pediatric supplement queries.</div></div></div><p class='text-gray-400 text-sm'>BrainRich Kids targeted the underserved intersection of cognitive development and clean-ingredient kids supplements — a keyword cluster where established brands had thin, generic content.</p></div>",
    "broc-shot": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Avmacol</div><div class='text-xs text-blue-400 mb-2'>Clinical Brand</div><div class='text-sm text-gray-400'>Leverages clinical trial citations and research-backed positioning to rank on high-intent sulforaphane queries. Their scientific credibility makes them a default reference for informed buyers.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Jarrow Formulas</div><div class='text-xs text-blue-400 mb-2'>Supplement Authority</div><div class='text-sm text-gray-400'>Broad domain authority across hundreds of supplement categories gives Jarrow natural ranking power on broccoli sprout and sulforaphane product queries. Their scale is the competitive moat.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Johns Hopkins Research Pages</div><div class='text-xs text-blue-400 mb-2'>Editorial Dominance</div><div class='text-sm text-gray-400'>Institutional research pages from Johns Hopkins occupy top positions on informational sulforaphane queries, shaping buyer education before any product page enters the picture.</div></div></div><p class='text-gray-400 text-sm'>Broc Shot found opportunity by bridging the gap between dense research content and accessible consumer education — ranking where clinical pages were too technical and product pages were too thin.</p></div>",
    "cast-nets": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Betts</div><div class='text-xs text-blue-400 mb-2'>Legacy Brand</div><div class='text-sm text-gray-400'>A heritage cast net brand with decades of wholesale distribution and brand recognition baked into fishing culture. Their name alone drives branded and comparison search traffic.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Ahi USA</div><div class='text-xs text-blue-400 mb-2'>Amazon-First Competitor</div><div class='text-sm text-gray-400'>Strong product listing presence on Amazon captures high-intent buyers before they reach brand sites. Their marketplace dominance makes direct organic competition difficult on pure product queries.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Bass Pro / Cabela's</div><div class='text-xs text-blue-400 mb-2'>Mega-Retailer</div><div class='text-sm text-gray-400'>Massive domain authority across all fishing categories means these retailers rank broadly on cast net queries without dedicated content investment. Their scale is nearly impossible to outrank directly.</div></div></div><p class='text-gray-400 text-sm'>Cast Nets competed by owning educational and technique-driven queries — how-to content, net selection guides, and species-specific use cases — where mega-retailers had no content depth.</p></div>",
    "catch": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Rapala</div><div class='text-xs text-blue-400 mb-2'>Iconic Brand</div><div class='text-sm text-gray-400'>One of fishing's most recognized names, Rapala's domain authority and backlink profile make them a default ranker across lure and bait queries globally. Their brand equity doubles as an SEO asset.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Berkley Fishing</div><div class='text-xs text-blue-400 mb-2'>Category Leader</div><div class='text-sm text-gray-400'>Widespread retail placement and heavy editorial coverage position Berkley as the authority on fishing bait across both informational and commercial queries. Their content investment is substantial.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>LIVETARGET</div><div class='text-xs text-blue-400 mb-2'>Premium Lure Brand</div><div class='text-sm text-gray-400'>Targets the same premium buyer segment with realistic lure designs and strong review presence on fishing enthusiast sites. They compete directly on high-consideration purchase queries.</div></div></div><p class='text-gray-400 text-sm'>Catch (catchbio.com) identified ranking opportunity in biology-driven fishing content — species behavior, bait science, and water conditions — where legacy brands had broad authority but shallow depth.</p></div>",
    "charity-miles": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Strava</div><div class='text-xs text-blue-400 mb-2'>Dominant Fitness App</div><div class='text-sm text-gray-400'>The runaway leader in fitness tracking with an enormous content library and community-generated SEO footprint. Strava owns most high-volume fitness app and running queries by default.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>MapMyRun</div><div class='text-xs text-blue-400 mb-2'>Under Armour-Backed</div><div class='text-sm text-gray-400'>Backed by Under Armour's brand authority and marketing infrastructure, MapMyRun holds strong positions on running app and route-tracking queries with consistent editorial investment.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Charity: Water</div><div class='text-xs text-blue-400 mb-2'>Editorial Authority</div><div class='text-sm text-gray-400'>Dominates the editorial space where charity giving and fitness motivation overlap, capturing informational queries that sit at the top of Charity Miles' unique conversion funnel.</div></div></div><p class='text-gray-400 text-sm'>Charity Miles carved out ranking space at the intersection of fitness apps and cause-driven giving — a keyword cluster too niche for fitness giants and too active for pure charity brands.</p></div>",
    "chill-frog": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Charlotte's Web</div><div class='text-xs text-blue-400 mb-2'>Category Authority</div><div class='text-sm text-gray-400'>The most recognized name in hemp-derived CBD, Charlotte's Web holds deep domain authority built on years of educational content and press coverage. They rank broadly across informational and commercial CBD queries.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>cbdMD</div><div class='text-xs text-blue-400 mb-2'>SEO-Invested Competitor</div><div class='text-sm text-gray-400'>Known for aggressive keyword targeting across the full CBD spectrum, cbdMD has built substantial content depth on gummy, dosage, and benefit queries that overlap directly with Chill Frog's audience.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Sunday Scaries</div><div class='text-xs text-blue-400 mb-2'>Brand-First CBD</div><div class='text-sm text-gray-400'>Strong editorial and review placement gives Sunday Scaries outsized organic visibility relative to their size. Their brand voice resonates with the anxiety-relief buyer segment Chill Frog also targets.</div></div></div><p class='text-gray-400 text-sm'>Chill Frog found traction in the calm and stress-relief CBD query cluster — benefit-specific searches where category giants had broad coverage but weak topical depth.</p></div>",
    "cricket-store-online": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Sports Direct</div><div class='text-xs text-blue-400 mb-2'>Mega-Retailer</div><div class='text-sm text-gray-400'>Enormous domain authority across all sporting equipment categories allows Sports Direct to rank on cricket gear queries without dedicated content investment. Their scale is a structural advantage.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Gray-Nicolls</div><div class='text-xs text-blue-400 mb-2'>Heritage Brand</div><div class='text-sm text-gray-400'>A centuries-old cricket brand whose name recognition drives branded and comparison searches. Gray-Nicolls' legacy status means they appear naturally in editorial roundups and equipment guides.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>eBay / Amazon</div><div class='text-xs text-blue-400 mb-2'>Marketplace Dominance</div><div class='text-sm text-gray-400'>Product listing pages occupy significant SERP real estate on equipment queries, intercepting buyers before they reach specialist retailers with actual expertise.</div></div></div><p class='text-gray-400 text-sm'>Cricket Store Online competed by building specialist content depth — bat selection guides, equipment comparisons, and skill-level recommendations — that mega-retailers and marketplaces never produce.</p></div>",
    "culprit-underwear": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>MeUndies</div><div class='text-xs text-blue-400 mb-2'>DTC Leader</div><div class='text-sm text-gray-400'>The dominant direct-to-consumer underwear brand with substantial content and backlink authority around comfort, subscription, and men's basics queries. Their editorial footprint is wide.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Tommy John</div><div class='text-xs text-blue-400 mb-2'>Premium Positioning</div><div class='text-sm text-gray-400'>Strong brand SEO and premium positioning allow Tommy John to rank competitively on high-intent men's underwear queries. Their review presence and media coverage reinforce domain authority.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Saxx</div><div class='text-xs text-blue-400 mb-2'>Performance Underwear</div><div class='text-sm text-gray-400'>Dominates editorial review rankings for performance and athletic underwear, capturing the active-lifestyle buyer segment with consistent placement in best-of guides and comparison articles.</div></div></div><p class='text-gray-400 text-sm'>Culprit Underwear targeted the style-forward men's underwear cluster — design, fit, and fabric queries where performance brands had weak content and basics brands had no positioning.</p></div>",
    "dadfuel": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Legion Athletics</div><div class='text-xs text-blue-400 mb-2'>Men's Supplement Authority</div><div class='text-sm text-gray-400'>One of the most content-invested brands in the supplement space, Legion ranks broadly across men's health, fitness, and nutrition queries. Their blog volume and backlink profile are formidable.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Transparent Labs</div><div class='text-xs text-blue-400 mb-2'>Science-First Brand</div><div class='text-sm text-gray-400'>Strong review site presence and science-backed positioning give Transparent Labs competitive rankings on research-intent supplement queries. Their authority with informed male buyers is substantial.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Ritual</div><div class='text-xs text-blue-400 mb-2'>DTC Supplement Leader</div><div class='text-sm text-gray-400'>Ritual's brand-first content strategy and editorial coverage have built strong domain authority across daily supplement and men's health queries, capturing broad awareness and consideration traffic.</div></div></div><p class='text-gray-400 text-sm'>DadFuel identified a gap in the dad-specific wellness query cluster — energy, recovery, and lifestyle supplements framed around fatherhood — where general men's brands had no targeted content.</p></div>",
    "dailysale": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Woot</div><div class='text-xs text-blue-400 mb-2'>Amazon-Backed</div><div class='text-sm text-gray-400'>Backed by Amazon's domain authority and infrastructure, Woot ranks almost effortlessly on deal and flash sale queries. Their parent company's link equity is an insurmountable structural advantage.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Groupon</div><div class='text-xs text-blue-400 mb-2'>Established Deals Brand</div><div class='text-sm text-gray-400'>Groupon's massive SEO footprint spans local deals, product discounts, and experience offers, giving them broad ranking coverage across the full deals and savings keyword landscape.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>SlickDeals</div><div class='text-xs text-blue-400 mb-2'>Community-Driven</div><div class='text-sm text-gray-400'>User-generated deal submissions and community voting create a constant stream of fresh, indexed content. SlickDeals' UGC model gives them ranking power on long-tail deal queries at scale.</div></div></div><p class='text-gray-400 text-sm'>DailySale targeted curated product deal queries — category-specific savings and brand discount searches — where community platforms had noise and mega-sites had no editorial curation.</p></div>",
    "dairypill": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Lactaid</div><div class='text-xs text-blue-400 mb-2'>Category Leader</div><div class='text-sm text-gray-400'>Decades of brand authority and retail ubiquity make Lactaid the default answer for dairy digestion queries. Their name recognition alone generates organic rankings that newer brands must build content to compete with.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Digestive Advantage</div><div class='text-xs text-blue-400 mb-2'>Retail Distribution</div><div class='text-sm text-gray-400'>Widespread shelf presence and brand recognition give Digestive Advantage strong commercial query rankings. Their retail authority translates directly into organic visibility on digestive supplement searches.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>NOW Foods</div><div class='text-xs text-blue-400 mb-2'>Supplement Authority</div><div class='text-sm text-gray-400'>NOW Foods' broad supplement catalog and established domain authority allow them to rank across digestive enzyme and dairy intolerance queries without a dedicated content strategy.</div></div></div><p class='text-gray-400 text-sm'>DairyPill found opportunity in the dairy sensitivity education cluster — symptom, ingredient, and comparison queries where category leaders had brand pages but no informational depth.</p></div>",
    "emf-harmony": "<div class='competitor-section'><h3 class='text-xl font-bold text-white mb-4'>The Competitive Landscape</h3><div class='grid grid-cols-1 md:grid-cols-3 gap-4 mb-6'><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>DefenderShield</div><div class='text-xs text-blue-400 mb-2'>Content Authority</div><div class='text-sm text-gray-400'>The most content-invested brand in the EMF protection space, DefenderShield ranks broadly on educational queries about EMF risks and protection strategies. Their editorial depth is the benchmark.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>Blushield</div><div class='text-xs text-blue-400 mb-2'>Direct Competitor</div><div class='text-sm text-gray-400'>A direct competitor with similar EMF harmonizing technology positioning. Blushield targets the same buyer audience and competes on the same product and comparison queries.</div></div><div class='rounded-xl p-4' style='background:#0a0f1e; border:1px solid #1f2937;'><div class='font-bold text-white mb-1'>SaferTech / EWG</div><div class='text-xs text-blue-400 mb-2'>Editorial Dominance</div><div class='text-sm text-gray-400'>Non-commercial editorial domains with decades of trust signals dominate the top informational EMF queries, capturing buyer research before any product page enters the picture.</div></div></div><p class='text-gray-400 text-sm'>EMF Harmony targeted device-specific and solution-intent queries — searches for protection by room, device type, and use case — where editorial sites had no product depth.</p></div>",
}

BOILERPLATE_PATTERN = re.compile(
    r'<p[^>]*>\s*Being absent from page 1 means losing customers.*?real buyer search behavior[^<]*(?:targeting[^<]*)?\s*</p>',
    re.DOTALL | re.IGNORECASE
)
BOILERPLATE_PATTERN2 = re.compile(
    r'Being absent from page 1 means losing customers.*?real buyer search behavior[^.]*\.',
    re.DOTALL | re.IGNORECASE
)

modified = []
for slug, new_section in replacements.items():
    path = f'{base}/{slug}/index.html'
    html = open(path).read()
    original = html

    replaced = False
    for pat in [BOILERPLATE_PATTERN, BOILERPLATE_PATTERN2]:
        match = pat.search(html)
        if match:
            html = html[:match.start()] + new_section + html[match.end():]
            replaced = True
            break

    if replaced:
        open(path, 'w').write(html)
        modified.append(slug)
        print(f"Fixed: {slug}")
    else:
        print(f"Pattern not found: {slug}")

print(f"\nModified: {len(modified)}/{len(replacements)}")
